#!/bin/bash

# ==============================================================================
# AUTOMATED DNSFILTER RELAY SETUP SCRIPT (UNIVERSAL)
# Supported: Ubuntu 20.04/22.04+, Debian 10/11/12
# ==============================================================================

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (sudo ./setup_relay.sh)"
  exit
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
    DIST=$ID
    VER=$VERSION_ID
else
    echo "OS NOT DETECTED. Aborting."
    exit 1
fi

clear
echo "========================================================"
echo "   DNSFilter Relay - Universal Installer"
echo "   Detected OS: $OS ($VER)"
echo "========================================================"

# --- PHASE 1: INPUT COLLECTION ---
echo ""
echo "--- 1. Configuration Inputs ---"

# Hostname
read -p "Enter desired Hostname (e.g., dns-relay): " NEW_HOSTNAME

# Credentials Setup (Optional)
echo ""
echo "If you need to reset the root password, enter it below. Leave blank to skip."
read -s -p "New Root Password (leave blank to skip): " ROOT_PASS
echo ""

# Network Configuration
echo ""
echo "--- Network Configuration ---"
# Detect interface
DETECTED_IFACE=$(ip -o -4 route show to default | awk '{print $5}' | head -n1)
read -p "Interface Name [default: $DETECTED_IFACE]: " IFACE_NAME
IFACE_NAME=${IFACE_NAME:-$DETECTED_IFACE}

read -p "Static IP with CIDR (e.g., 192.168.200.5/24): " STATIC_IP
read -p "Gateway IP (e.g., 192.168.200.1): " GATEWAY_IP
read -p "Primary DNS for OS (DNSFilter Primary): " DNS_PRI
read -p "Secondary DNS for OS (Google): " DNS_SEC

echo "Enter Search Domains separated by commas (e.g. curvelake.ca, corp.local)"
read -p "Search Domains: " SEARCH_DOMAIN_INPUT

# DNSFilter Config
echo ""
echo "--- DNSFilter Relay Configuration ---"
read -p "Site/Network Name (e.g., Your Network): " RELAY_NAME
read -p "Secret Key: " RELAY_SECRET

echo "Enter Local DNS Server IPs separated by commas (e.g. 192.168.1.7, 192.168.1.8)"
read -p "Local DNS IPs: " LOCAL_DNS_IP_INPUT

echo "Enter Local Domains separated by commas (e.g. corp.loc, files.loc)"
read -p "Local Domains: " LOCAL_DOMAINS_INPUT

# Determine Jumpbox IP for SSH
read -p "Jumpbox/Management IP for SSH Access (e.g., 10.0.0.50): " JUMPBOX_IP

echo ""
echo "========================================================"
echo "Installing... Do not close this session."
echo "========================================================"

# --- PHASE 2: SYSTEM PREP ---

# Set Hostname
hostnamectl set-hostname "$NEW_HOSTNAME"
echo "Hostname set to $NEW_HOSTNAME"

# Update System
echo "Updating repositories and upgrading packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get upgrade -y
# Ensure curl, ufw, and gnupg are present (Debian minimal sometimes lacks these)
apt-get install -y cron wget nano unzip unattended-upgrades ufw curl gnupg

# --- PHASE 3: RESOLVED CONFIGURATION ---
# Debian 10/11/12 often doesn't use systemd-resolved by default, but Ubuntu does.
# We check if it is active before trying to configure it.

if systemctl is-active --quiet systemd-resolved; then
    echo "Configuring systemd-resolved to free up port 53..."
    sed -i 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
    sed -i "s/#DNS=/DNS=$DNS_PRI $DNS_SEC/" /etc/systemd/resolved.conf
    ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
    systemctl restart systemd-resolved
    echo "Systemd-resolved configured."
else
    echo "Systemd-resolved not active/present. Skipping StubListener config."
    # For standard Debian, we ensure resolv.conf points to upstream DNS temporarily
    echo "nameserver $DNS_PRI" > /etc/resolv.conf
    echo "nameserver $DNS_SEC" >> /etc/resolv.conf
fi

# --- PHASE 4: DNSFILTER RELAY INSTALLATION ---

echo "Downloading and installing Relay binary..."
mkdir -p /bin/relay
cd /bin/relay

wget -q https://download.dnsfilter.com/Relay/relay-linux-amd64
chmod +x relay-linux-amd64

# --- PHASE 4.5: INPUT FORMATTING ---
# 1. Format Local Domains
FORMATTED_LOCAL_DOMAINS=$(echo "$LOCAL_DOMAINS_INPUT" | awk -F, '{for(i=1;i<=NF;i++){gsub(/^ *| *$/,"",$i); printf "\"%s\"", $i; if(i<NF) printf ", "}}')
# 2. Format Search Domains (for config file)
FORMATTED_SEARCH_DOMAINS=$(echo "$SEARCH_DOMAIN_INPUT" | awk -F, '{for(i=1;i<=NF;i++){gsub(/^ *| *$/,"",$i); printf "\"%s\"", $i; if(i<NF) printf ", "}}')
# 3. Format Search Domains (Space separated for Debian Interfaces file)
SPACE_SEARCH_DOMAINS=$(echo "$SEARCH_DOMAIN_INPUT" | awk -F, '{for(i=1;i<=NF;i++){gsub(/^ *| *$/,"",$i); printf "%s ", $i}}')
# 4. Format Local DNS IPs (Appends :53)
FORMATTED_LOCAL_DNS_IPS=$(echo "$LOCAL_DNS_IP_INPUT" | awk -F, '{for(i=1;i<=NF;i++){gsub(/^ *| *$/,"",$i); printf "\"%s:53\"", $i; if(i<NF) printf ", "}}')

# --- PHASE 5: RELAY CONFIGURATION ---

echo "Generating relay.conf..."
cat > /bin/relay/relay.conf <<EOF
# Generated by Automation Script
[client]
  name = "$RELAY_NAME"
  secret_key = "$RELAY_SECRET"

[[local_dns_server]]
  addresses = [ $FORMATTED_LOCAL_DNS_IPS ]
  local_domains = [ $FORMATTED_LOCAL_DOMAINS ]

# Networking
so_reuse_port = true
upstream_order = [ "udp", "tcp", "tcp-tls" ]

[log]
  level = "error"
EOF

# --- PHASE 6: SERVICE CREATION ---

echo "Creating Systemd Service..."
cat > /lib/systemd/system/relay.service <<EOF
[Unit]
Description=DNSFilter Relay Service
After=network.target

[Service]
Type=simple
ExecStart=/bin/relay/relay-linux-amd64 -c /bin/relay/relay.conf
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable relay.service
systemctl start relay.service
echo "Relay service started."

# --- PHASE 7: SECURITY & MAINTENANCE ---

echo "Configuring Firewall (UFW)..."
# Check if UFW is actually running/enabled, if not enable it
ufw allow 53/tcp
ufw allow 53/udp
if [ ! -z "$JUMPBOX_IP" ]; then
    ufw allow from "$JUMPBOX_IP" to any port 22
else
    echo "Warning: No Jumpbox IP provided. Allowing SSH from ANYWHERE."
    ufw allow 22
fi
echo "y" | ufw enable

echo "Configuring Unattended Upgrades..."
cat > /etc/apt/apt.conf.d/20auto-upgrades <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

# --- PHASE 8: NETWORK CHANGES (LAST STEP) ---

# Handle Root Password Reset if requested
if [ ! -z "$ROOT_PASS" ]; then
    echo "root:$ROOT_PASS" | chpasswd
    echo "Root password updated."
fi

echo "Setting up Networking..."

# Clean up static IP string (remove CIDR for Debian address field if needed, but 'ip addr' style usually accepts CIDR)
# For Debian /etc/network/interfaces, we need Address and Netmask usually, but modern iproute2 handles CIDR.
# However, traditional ifupdown prefers address and netmask separately or CIDR in address line depending on version.
# We will use the CIDR in 'address' line which is supported in Debian 10+.

if [[ "$DIST" == "ubuntu" ]]; then
    # --- UBUNTU (NETPLAN) ---
    echo "Detected Ubuntu. Configuring Netplan..."
    
    mkdir -p /etc/cloud/cloud.cfg.d
    echo "network: {config: disabled}" > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    rm -rf /etc/netplan/*
    
    cat > /etc/netplan/01-wired-interface-1.yaml <<EOF
network:
    ethernets:
        $IFACE_NAME:
            dhcp4: no
            dhcp6: no
            addresses:
            - $STATIC_IP
            nameservers:
                addresses:
                - $DNS_PRI
                - $DNS_SEC
                search: [ $FORMATTED_SEARCH_DOMAINS ]
            routes:
            -   to: default
                via: $GATEWAY_IP
    version: 2
EOF
    chmod 600 /etc/netplan/01-wired-interface-1.yaml
    
    echo "========================================================"
    echo "SETUP COMPLETE (Ubuntu)."
    echo "========================================================"
    echo "Applying Netplan changes..."
    netplan generate
    netplan apply

elif [[ "$DIST" == "debian" ]]; then
    # --- DEBIAN (INTERFACES) ---
    echo "Detected Debian. Configuring /etc/network/interfaces..."
    
    # Backup existing
    cp /etc/network/interfaces /etc/network/interfaces.bak
    
    # Write new config
    cat > /etc/network/interfaces <<EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto $IFACE_NAME
iface $IFACE_NAME inet static
    address $STATIC_IP
    gateway $GATEWAY_IP
    dns-nameservers $DNS_PRI $DNS_SEC
    dns-search $SPACE_SEARCH_DOMAINS
EOF

    echo "========================================================"
    echo "SETUP COMPLETE (Debian)."
    echo "========================================================"
    echo "Restarting networking..."
    echo "WARNING: SSH connection may drop."
    
    # Flush current IP to ensure clean slate, then restart networking
    ip addr flush dev $IFACE_NAME
    systemctl restart networking
else
    echo "Unknown distribution logic for network. Network config skipped."
fi
